apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline-hello-world
  name: pipeline-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-hello-world
  template:
    metadata:
      labels:
        app: pipeline-hello-world
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/hello-tekton-buildah-demo/springboot-hello-world:latest
        imagePullPolicy: Always
        name: pipeline-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
