apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-hello-world
  name: springboot-hello-world
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-hello-world
